name: ci
on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14]
    name: 'v${{ matrix.node }} lint, test and build'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Run validate
        run: npm run validate
