name: CI

on:
  push:
    branches:
      - 'main'
  pull_request: {}

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies & cache
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: true

      - name: Run tests
        run: npm run test:ci

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies & cache
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: true

      - name: Run lint
        run: npm run lint

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies & cache
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: true

      - name: Run build
        run: npm run build
